Add feature to navigate and display files within the current working directory.
CupOfGeo/adaptable-antelopes pull request #24
Opened 2021-07-11 23:06 UTC by ntdkhiem

2021-07-11 23:30 UTC, BoraxTheClean requested changes
We should remove the files in the `notes/`dir.

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
> +    kb.add("s-tab")(focus_previous)
Should we also add arrow keys here (and maybe even vim bindings)?

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
> +    kb.add("s-tab")(focus_previous)
We should also have a keyboard shortcut that opens a file, like enter.

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
> +            pass
I'm running this locally and clicking on a directory doesn't do anything.

It seems like that is intentional, should we add some placeholder functionality and add a Issue to implement that?

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
>      application.run()
Since we're not going to be running `scroll_menu.py` locally to invoke the application, this should be hooked up to the text_editor code.

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
> +                    handler=functools.partial(self.display_content, item, "."),
If `"."` is the directory path parameter in `self.display_content`, can we make that  a constant?

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
> +    """Main class for scrollable menu"""
```suggestion
    """
    Scrollable Menu UI Element.
    
    Displays contents of the a given working directory and allows users to inspect files. 
    In the future users can drill down into directories.
    """
```
Does this description look good to you? You can commit it from the PR UI.

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
> +            padding=1,
Can we make these a constant?

2021-07-11 23:30 UTC, BoraxTheClean commented on scroll_menu.py
> +        If the target_content is a directory, replace the right column with its content.
This is a TODO
```suggestion
        TODO: If the target_content is a directory, replace the right column with its content.
```

2021-07-11 23:37 UTC, BoraxTheClean commented on scroll_menu.py
> +            pass
From @CupOfGeo: We also need an ⬆️ move up on directory button for this use case.

2021-07-11 23:38 UTC, CupOfGeo approved these changes

2021-07-12 12:12 UTC, BoraxTheClean approved these changes

2021-07-12 12:53 UTC, CupOfGeo approved these changes

2021-07-12 12:53 UTC, CupOfGeo commented on src/constants.py
> +PADDING_WIDTH = 1
I don't know if you need a whole file for this you can just add them to the top of scroll menu for readability and more flexible to change

2021-07-12 13:27 UTC, merged